apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint-config
  namespace: gpt
data:
  entrypoint.sh: |
    #!/bin/bash
    set -e
    
    echo "🚀 Starting Trading Pod..."
    echo "PAPER_TRADE: $PAPER_TRADE"
    echo "GCP_PROJECT_ID: $GCP_PROJECT_ID"
    echo "PYTHONPATH: $PYTHONPATH"
    echo "RUNNER_SCRIPT: $RUNNER_SCRIPT"
    
    # Set up Python path
    export PYTHONPATH="/app:/app/runner:$PYTHONPATH"
    
    # Create __init__.py files if they don't exist
    touch /app/__init__.py 2>/dev/null || true
    touch /app/runner/__init__.py 2>/dev/null || true
    
    # Navigate to app directory
    cd /app
    
    # Execute the runner script specified in environment variable
    if [ -n "$RUNNER_SCRIPT" ]; then
        echo "🏃 Running: $RUNNER_SCRIPT"
        exec python "$RUNNER_SCRIPT"
    else
        echo "❌ No RUNNER_SCRIPT specified, defaulting to main runner..."
        exec python runner/main_runner_combined.py
    fi 