apiVersion: apps/v1
kind: Deployment
metadata:
  name: tron-frontend-deployment
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tron-frontend
  template:
    metadata:
      labels:
        app: tron-frontend
    spec:
      serviceAccountName: gpt-runner-sa
      containers:
        - name: tron-frontend
          image: asia-south1-docker.pkg.dev/autotrade-453303/tron-system/tron-frontend:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: tron-frontend-service
  namespace: gpt
spec:
  selector:
    app: tron-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer 