apiVersion: apps/v1
kind: Deployment
metadata:
  name: futures-trader
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: futures-trader
  template:
    metadata:
      labels:
        app: futures-trader
    spec:
      serviceAccountName: gpt-runner-sa
      containers:
        - name: futures-trader
          image: asia-south1-docker.pkg.dev/autotrade-453303/gpt-repo/futures-trader:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
          env:
           - name: RUNNER_SCRIPT
             value: futures_trading/futures_runner.py
