apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-runner
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-runner
  template:
    metadata:
      labels:
        app: main-runner
    spec:
      serviceAccountName: gpt-runner-sa
      containers:
        - name: main-runner
          image: asia-south1-docker.pkg.dev/autotrade-453303/gpt-repo/gpt-runner:latest
          command: ["/bin/bash", "-c"]
          args: 
            - |
              echo "Starting main runner with RAG/FAISS fixes..."
              cd /app
              
              # Create the missing __init__.py file for gpt_runner.rag package
              mkdir -p gpt_runner/rag
              echo "# Makes rag a Python package" > gpt_runner/rag/__init__.py
              
              # Fix the import in runner/gpt_runner.py  
              sed -i 's/from gpt_runner.gpt_self_improvement_monitor/from gpt_runner.rag.gpt_self_improvement_monitor/' runner/gpt_runner.py
              
              echo "Package structure fixed, running main_runner_combined.py..."
              python3 runner/main_runner_combined.py
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: RUNNER_SCRIPT
              value: runner/main_runner_combined.py
