apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-runner
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-runner
  template:
    metadata:
      labels:
        app: main-runner
    spec:
      containers:
        - name: main-runner
          image: asia-south1-docker.pkg.dev/autotrade-453303/gpt-repo/gpt-runner:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
