apiVersion: apps/v1
kind: Deployment
metadata:
  name: options-trader
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: options-trader
  template:
    metadata:
      labels:
        app: options-trader
    spec:
      serviceAccountName: gpt-runner-sa
      containers:
        - name: options-trader
          image: asia-south1-docker.pkg.dev/autotrade-453303/gpt-repo/options-trader:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
          env:
            - name: RUNNER_SCRIPT
              value: options_trading/options_runner.py
