---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpt-runner-sa
  namespace: gpt
  annotations:
    iam.gke.io/gcp-service-account: gpt-runner-sa@autotrade-453303.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpt-runner-sa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: gpt-runner-sa
  namespace: gpt
---
# Additional role for secrets access within namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gpt-runner-secrets-role
  namespace: gpt
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gpt-runner-secrets-binding
  namespace: gpt
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gpt-runner-secrets-role
subjects:
- kind: ServiceAccount
  name: gpt-runner-sa
  namespace: gpt 