# stock-trader.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-trader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-trader
  template:
    metadata:
      labels:
        app: stock-trader
    spec:
      serviceAccountName: gpt-runner-sa
      automountServiceAccountToken: true
      containers:
      - name: stock-trader
        image: asia-south1-docker.pkg.dev/autotrade-453303/gpt-repo/gpt-runner:latest
        env:
        - name: PAPER_MODE
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: " 512Mi"
            cpu: "500m"
