apiVersion: batch/v1
kind: Job
metadata:
  name: stock-trader
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-trader
  template:
    metadata:
      labels:
        app: stock-trader
    spec:
      containers:
        - name: stock-trader
          image: asia-south1-docker.pkg.dev/autotrade-453303/gpt-repo/stock-trader:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
