apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-trader
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-trader
  template:
    metadata:
      labels:
        app: stock-trader
    spec:
      serviceAccountName: gpt-runner-sa
      containers:
        - name: stock-trader
          image: asia-south1-docker.pkg.dev/autotrade-453303/gpt-repo/stock-trader:latest
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"
          env:
            - name: RUNNER_SCRIPT
              value: stock_trading/stock_runner.py
