server {
    listen 80;
    server_name _;

    # Proxy to the frontend Next.js service
    location / {
        proxy_pass http://frontend:3000; # The service name 'frontend' and port '3000'
        try_files $uri $uri/ /index.html; # Handle client-side routing
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # API Gateway to the backend service
    location /api/ {
        proxy_pass http://tron-backend:8000/; # The service name 'tron-backend' and port '8000'
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
    }

    # Error pages
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
} 