apiVersion: apps/v1
kind: Deployment
metadata:
  name: tron-backend
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tron-backend
  template:
    metadata:
      labels:
        app: tron-backend
    spec:
      serviceAccountName: gpt-runner-sa
      containers:
      - name: backend
        image: asia-south1-docker.pkg.dev/autotrade-453303/tron-system/tron-backend:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: tron-backend-service
  namespace: gpt
spec:
  selector:
    app: tron-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt-main-runner
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt-main-runner
  template:
    metadata:
      labels:
        app: gpt-main-runner
    spec:
      serviceAccountName: gpt-runner-sa
      containers:
      - name: main-runner
        image: asia-south1-docker.pkg.dev/autotrade-453303/tron-system/gpt-runner:latest
        env:
        - name: RUNNER_TYPE
          value: "main"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-trader
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-trader
  template:
    metadata:
      labels:
        app: stock-trader
    spec:
      serviceAccountName: gpt-runner-sa
      containers:
      - name: stock-trader
        image: asia-south1-docker.pkg.dev/autotrade-453303/tron-system/stock-trader:latest
        env:
        - name: RUNNER_TYPE
          value: "stock"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 300m
            memory: 512Mi 