apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-trader
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-trader
  template:
    metadata:
      labels:
        app: stock-trader
    spec:
      serviceAccountName: gpt-runner-sa
      containers:
      - name: stock-trader
        image: asia-south1-docker.pkg.dev/autotrade-453303/tron-system/stock-trader:latest
        env:
        - name: PAPER_TRADE
          value: "true"
        - name: GCP_PROJECT_ID
          value: "autotrade-453303"
        - name: PYTHONPATH
          value: "/app:/app/runner:/app/stock_trading"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: entrypoint
          mountPath: /entrypoint.sh
          subPath: entrypoint.sh
      volumes:
      - name: entrypoint
        configMap:
          name: entrypoint-config
          defaultMode: 0755
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: options-trader
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: options-trader
  template:
    metadata:
      labels:
        app: options-trader
    spec:
      serviceAccountName: gpt-runner-sa
      containers:
      - name: options-trader
        image: asia-south1-docker.pkg.dev/autotrade-453303/tron-system/options-trader:latest
        env:
        - name: PAPER_TRADE
          value: "true"
        - name: GCP_PROJECT_ID
          value: "autotrade-453303"
        - name: PYTHONPATH
          value: "/app:/app/runner:/app/options_trading"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: entrypoint
          mountPath: /entrypoint.sh
          subPath: entrypoint.sh
      volumes:
      - name: entrypoint
        configMap:
          name: entrypoint-config
          defaultMode: 0755
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: futures-trader
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: futures-trader
  template:
    metadata:
      labels:
        app: futures-trader
    spec:
      serviceAccountName: gpt-runner-sa
      containers:
      - name: futures-trader
        image: asia-south1-docker.pkg.dev/autotrade-453303/tron-system/futures-trader:latest
        env:
        - name: PAPER_TRADE
          value: "true"
        - name: GCP_PROJECT_ID
          value: "autotrade-453303"
        - name: PYTHONPATH
          value: "/app:/app/runner:/app/futures_trading"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: entrypoint
          mountPath: /entrypoint.sh
          subPath: entrypoint.sh
      volumes:
      - name: entrypoint
        configMap:
          name: entrypoint-config
          defaultMode: 0755
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-runner
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-runner
  template:
    metadata:
      labels:
        app: main-runner
    spec:
      serviceAccountName: gpt-runner-sa
      containers:
      - name: main-runner
        image: asia-south1-docker.pkg.dev/autotrade-453303/tron-system/gpt-runner:latest
        env:
        - name: PAPER_TRADE
          value: "true"
        - name: GCP_PROJECT_ID
          value: "autotrade-453303"
        - name: PYTHONPATH
          value: "/app:/app/runner"
        resources:
          requests:
            cpu: 300m
            memory: 768Mi
          limits:
            cpu: 800m
            memory: 1.5Gi
        volumeMounts:
        - name: entrypoint
          mountPath: /entrypoint.sh
          subPath: entrypoint.sh
      volumes:
      - name: entrypoint
        configMap:
          name: entrypoint-config
          defaultMode: 0755
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: entrypoint-config
  namespace: gpt
data:
  entrypoint.sh: |
    #!/bin/bash
    set -e
    echo "Starting trading pod..."
    echo "PAPER_TRADE: $PAPER_TRADE"
    echo "GCP_PROJECT_ID: $GCP_PROJECT_ID"
    echo "PYTHONPATH: $PYTHONPATH"
    
    # Wait for dependencies
    sleep 10
    
    # Execute the appropriate runner script
    exec python "$@" 