apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.futuresTrader.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.futuresTrader.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.futuresTrader.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Values.futuresTrader.name }}
          image: "{{ .Values.futuresTrader.image.repository }}:{{ .Values.futuresTrader.image.tag }}"
          command: ["/bin/bash"]
          args: ["/entrypoint.sh"]
          resources:
            {{- toYaml .Values.futuresTrader.resources | nindent 12 }}
          env:
            {{- range $key, $val := .Values.futuresTrader.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
            - name: GCP_PROJECT_ID
              value: "{{ .Values.gcpProjectId }}"
            - name: PYTHONPATH
              value: "/app:/app/runner:/app/futures_trading"
          volumeMounts:
            - name: entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
      volumes:
        - name: entrypoint
          configMap:
            name: entrypoint-config
            defaultMode: 0755 