apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.logAggregator.name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.logAggregator.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.logAggregator.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      volumes:
        - name: gcp-key
          secret:
            secretName: gcp-service-account-key
            optional: true
      containers:
        - name: {{ .Values.logAggregator.name }}
          image: "{{ .Values.logAggregator.image.repository }}:{{ .Values.global.imageTag | default .Values.logAggregator.image.tag }}"
          imagePullPolicy: {{ .Values.logAggregator.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.logAggregator.service.port }}
          env:
            - name: GCP_PROJECT_ID
              value: {{ .Values.gcpProjectId | quote }}
            - name: FIRESTORE_PROJECT_ID
              value: {{ .Values.gcpProjectId | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.environment | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: API_PORT
              value: {{ .Values.logAggregator.env.API_PORT | default "8001" | quote }}
            - name: GCS_BUCKET_NAME
              value: {{ .Values.logAggregator.env.GCS_BUCKET_NAME | default "tron-trade-logs" | quote }}
            - name: KUBERNETES_NAMESPACE
              value: {{ .Values.namespace | quote }}
            - name: AUTH_ENABLED
              value: {{ .Values.logAggregator.env.AUTH_ENABLED | default "false" | quote }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: openai-api-key
                  optional: true
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/key.json"
          volumeMounts:
            - name: gcp-key
              mountPath: /var/secrets/google
              readOnly: true
          resources:
            {{- toYaml .Values.logAggregator.resources | nindent 12 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.logAggregator.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.logAggregator.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.logAggregator.service.port }}
      targetPort: {{ .Values.logAggregator.service.port }}
  type: {{ .Values.logAggregator.service.type }} 