apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.optionsTrader.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.optionsTrader.name }}
    app.kubernetes.io/component: trading-engine
    app.kubernetes.io/part-of: tron-trading-system
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.optionsTrader.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.optionsTrader.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Values.optionsTrader.name }}
          image: "{{ .Values.optionsTrader.image.repository }}:{{ .Values.global.imageTag | default .Values.optionsTrader.image.tag }}"
          command: ["/bin/bash", "/entrypoint.sh"]
          args: ["{{ .Values.optionsTrader.env.RUNNER_SCRIPT }}"]
          ports:
            - containerPort: {{ .Values.optionsTrader.service.targetPort }}
              name: http
          resources:
            {{- toYaml .Values.optionsTrader.resources | nindent 12 }}
          env:
            - name: GCP_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: tron-system-config
                  key: GCP_PROJECT_ID
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: tron-system-config
                  key: ENVIRONMENT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: tron-system-config
                  key: LOG_LEVEL
            - name: MAIN_RUNNER_SERVICE
              valueFrom:
                configMapKeyRef:
                  name: tron-system-config
                  key: MAIN_RUNNER_SERVICE
            {{- range $key, $val := .Values.optionsTrader.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
            - name: PYTHONPATH
              value: "/app:/app/runner:/app/options_trading"
          volumeMounts:
            - name: entrypoint
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
          {{- if .Values.optionsTrader.healthCheck.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.optionsTrader.healthCheck.path }}
              port: {{ .Values.optionsTrader.healthCheck.port }}
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: {{ .Values.optionsTrader.healthCheck.path }}
              port: {{ .Values.optionsTrader.healthCheck.port }}
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          {{- else }}
          readinessProbe:
            exec:
              command:
                - pgrep
                - -f
                - "{{ .Values.optionsTrader.env.RUNNER_SCRIPT }}"
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - pgrep
                - -f
                - "{{ .Values.optionsTrader.env.RUNNER_SCRIPT }}"
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          {{- end }}
      volumes:
        - name: entrypoint
          configMap:
            name: entrypoint-config
            defaultMode: 0755