{{- if .Values.secrets.create | default true }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dashboard.secretName | default "dashboard-secrets" }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.dashboard.auth.username | default "admin" | b64enc }}
  password: {{ .Values.dashboard.auth.password | default (randAlphaNum 16) | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- if .Values.secrets.openaiApiKey }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.kiteApiKey }}
  kite-api-key: {{ .Values.secrets.kiteApiKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.kiteApiSecret }}
  kite-api-secret: {{ .Values.secrets.kiteApiSecret | b64enc }}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  GCP_PROJECT_ID: {{ .Values.gcpProjectId | default "autotrade-453303" | quote }}
  ENVIRONMENT: {{ .Values.environment | default "production" | quote }}
  PAPER_TRADE: {{ .Values.paperTrade | default true | quote }}
  LOG_LEVEL: {{ .Values.logLevel | default "INFO" | quote }}
  REAL_TIME_UPDATES: {{ .Values.realTimeUpdates | default true | quote }}
  AUTO_REFRESH_INTERVAL: {{ .Values.autoRefreshInterval | default 30 | quote }}
{{- end }}