apiVersion: v1
kind: Secret
metadata:
  name: trading-api-secrets
  namespace: gpt
type: Opaque
data:
  # Replace these with your actual base64-encoded secrets
  # echo -n 'your_api_key' | base64
  KITE_API_KEY: "YOUR_KITE_API_KEY_BASE64"
  KITE_API_SECRET: "YOUR_KITE_API_SECRET_BASE64"
  OPENAI_API_KEY: "YOUR_OPENAI_API_KEY_BASE64"
  SLACK_BOT_TOKEN: "YOUR_SLACK_BOT_TOKEN_BASE64" 