apiVersion: v1
kind: ConfigMap
metadata:
  name: market-holidays
  namespace: default
data:
  holidays.list: |
    # Indian Stock Market Holidays 2024 (NSE)
    # Format: YYYY-MM-DD
    2024-01-26 # Republic Day
    2024-03-08 # Mahashivratri
    2024-03-25 # Holi
    2024-03-29 # Good Friday
    2024-04-11 # Id-Ul-Fitr (Ramzan Eid)
    2024-04-17 # Ram Navami
    2024-05-01 # Maharashtra Day
    2024-06-17 # Bakri Id
    2024-07-17 # Moharram
    2024-08-15 # Independence Day
    2024-10-02 # Mahatma Gandhi Jayanti
    2024-11-01 # Diwali-Laxmi Pujan
    2024-11-15 # Gurunanak Jayanti
    2024-12-25 # Christmas 