apiVersion: batch/v1
kind: CronJob
metadata:
  name: options-trader-market-open-scaler
  namespace: gpt
spec:
  schedule: "30 3 * * 1-5" # 9:00 AM IST, Monday to Friday
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cronjob-scaler
          containers:
          - name: kubectl-scaler
            image: bitnami/kubectl:latest
            command:
            - "/bin/sh"
            - "-c"
            - "kubectl scale deployment/options-trader -n gpt --replicas=1"
          restartPolicy: OnFailure
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1 