# Development Environment Configuration
# Safe settings for development and testing

# Environment Settings
environment: "development"
paper_trade: true  # Always paper trade in development

# Capital Management - Conservative for testing
default_capital: 100000
max_daily_loss: 1000           # ₹1,000 max loss per day
max_daily_loss_pct: 1.0        # 1% max loss

# Position Limits - Reduced for safety
stock_position_limit: 0.05     # 5% max per stock
option_position_limit: 0.02    # 2% max per option
future_position_limit: 0.08    # 8% max per future

# Risk Management - Conservative
margin_utilization_limit: 0.30  # 30% max margin
max_volatility_threshold: 0.03  # 3% volatility limit

# API Settings - Reduced rate to avoid limits
api_rate_limit: 1              # 1 request per second
api_timeout: 15                # 15 seconds timeout

# Monitoring - Less frequent for development
monitoring_interval: 120       # 2 minutes
backup_frequency: 1200         # 20 minutes
auto_square_off_time: "15:10"  # Early square off

# Logging - More verbose for debugging
log_level: "DEBUG"

# Strategy Settings - Conservative
scalp_config:
  min_price: 100
  max_price: 110
  sl_buffer: 20               # Tighter stop loss
  target_buffer: 40           # Lower targets
  quantity: 25                # Smaller quantities

# Development-specific settings
development:
  mock_market_data: true
  simulate_latency: false
  enable_debug_mode: true
  test_mode: true

# Alert Settings - Disabled for development
alerts_email_enabled: false
alerts_slack_enabled: false

# Technical Indicators - Faster periods for testing
technical_indicators:
  rsi_period: 10
  atr_period: 10
  macd_fast: 8
  macd_slow: 21
  macd_signal: 7