# Production Environment Configuration
# Live trading settings with maximum safety and performance

# Environment Settings
environment: "production"
paper_trade: false  # LIVE TRADING - Set to true to override for safety

# Capital Management - Production amounts
default_capital: 1000000       # ₹10 Lakh starting capital
max_daily_loss: 50000          # ₹50,000 max loss per day
max_daily_loss_pct: 5.0        # 5% max loss (conservative)

# Position Limits - Production limits
stock_position_limit: 0.10     # 10% max per stock
option_position_limit: 0.05    # 5% max per option
future_position_limit: 0.15    # 15% max per future

# Risk Management - Strict production limits
margin_utilization_limit: 0.80  # 80% max margin utilization
max_volatility_threshold: 0.05  # 5% volatility circuit breaker

# API Settings - Production optimized
api_rate_limit: 3              # 3 requests per second (Kite limit)
api_timeout: 5                 # 5 seconds timeout (fast)

# Monitoring - Frequent production monitoring
monitoring_interval: 30        # 30 seconds
backup_frequency: 300          # 5 minutes
auto_square_off_time: "15:20"  # Standard square off time

# Logging - Production level (avoid DEBUG)
log_level: "INFO"

# Strategy Settings - Production optimized
scalp_config:
  min_price: 100
  max_price: 120
  sl_buffer: 30
  target_buffer: 60
  quantity: 75

# Production-specific settings
production:
  strict_risk_checks: true
  real_time_monitoring: true
  auto_circuit_breaker: true
  position_monitoring: true
  pnl_alerts: true

# Alert Settings - Full alerting in production
alerts_email_enabled: true
alerts_slack_enabled: true
alerts_webhook_url: ""  # Set your production webhook URL

# Performance Settings
performance:
  enable_caching: true
  cache_size: 1000
  optimize_calculations: true
  parallel_processing: true

# Options Settings - Full calculation
options:
  risk_free_rate: 0.065        # Current RBI rate
  use_real_time_iv: true
  calculate_full_greeks: true
  real_time_pricing: true

# Portfolio Settings - Production
portfolio:
  max_positions: 15
  correlation_limit: 0.8
  diversification_threshold: 0.25
  rebalance_frequency: 1800    # 30 minutes

# Circuit Breakers
circuit_breakers:
  max_consecutive_losses: 5
  max_drawdown_pct: 10.0
  volatility_spike_threshold: 0.08
  system_halt_conditions:
    - "critical_error"
    - "api_failure"
    - "risk_breach"

# Backup and Recovery
backup:
  auto_backup_positions: true
  backup_to_cloud: true
  recovery_mode: "conservative"

# Compliance
compliance:
  enable_audit_log: true
  position_limits_enforcement: true
  regulatory_reporting: true