apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Values.frontend.name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 3000
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: 3000
  type: {{ .Values.frontend.service.type }} 