apiVersion: v1
kind: ConfigMap
metadata:
  name: log-aggregator-config
  namespace: gpt
  labels:
    app: log-aggregator
    component: log-monitoring
data:
  # Application Configuration
  LOG_LEVEL: "INFO"
  API_HOST: "0.0.0.0"
  API_PORT: "8001"
  API_PREFIX: "/api/v1"
  WORKERS: "1"
  
  # GCP Configuration
  FIRESTORE_PROJECT_ID: "autotrade-453303"
  
  # Kubernetes Configuration
  KUBERNETES_NAMESPACE: "gpt"
  
  # OpenAI Configuration
  OPENAI_MODEL: "gpt-3.5-turbo"
  OPENAI_MAX_TOKENS: "1000"
  OPENAI_TEMPERATURE: "0.3"
  OPENAI_TIMEOUT: "30"
  
  # Performance Configuration
  MAX_LOG_ENTRIES: "1000"
  DEFAULT_PAGE_SIZE: "50"
  MAX_PAGE_SIZE: "500"
  
  # GPT Summarization Configuration
  MAX_TOKENS_FOR_SUMMARY: "500"
  SUMMARY_MODEL: "gpt-4o-mini"
  SUMMARY_TEMPERATURE: "0.3"
  
  # GCS Log Prefixes (JSON format)
  GCS_LOG_PREFIXES: '["trades/", "reflections/", "strategies/"]'
  
  # Firestore Collections (JSON format)
  FIRESTORE_COLLECTIONS: '["gpt_runner_trades", "gpt_runner_reflections"]' 