apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: log-aggregator-network-policy
  namespace: gpt
  labels:
    app: log-aggregator
    component: log-monitoring
spec:
  podSelector:
    matchLabels:
      app: log-aggregator
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from dashboard and other services in the same namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: gpt
    - podSelector:
        matchLabels:
          app: trading-dashboard
    ports:
    - protocol: TCP
      port: 8001
  # Allow traffic from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8001
  # Allow traffic from load balancer
  - from: []
    ports:
    - protocol: TCP
      port: 8001
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow HTTPS traffic for external APIs (OpenAI, GCP)
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTP traffic for internal services
  - to: []
    ports:
    - protocol: TCP
      port: 80
  # Allow Kubernetes API access
  - to: []
    ports:
    - protocol: TCP
      port: 6443 