apiVersion: v1
kind: Service
metadata:
  name: log-aggregator-service
  labels:
    app: log-aggregator
spec:
  selector:
    app: log-aggregator
  ports:
  - protocol: TCP
    port: 80 # Port exposed by the LoadBalancer
    targetPort: 8001 # Port on the pods (containerPort in deployment.yaml)
  type: LoadBalancer 