name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install numpy==1.23.5
          pip install faiss-cpu==1.7.4
          pip install flake8 bandit pytest
          pip install -r requirements.txt --no-deps  # Skip faiss
          pip install \
            google-cloud-firestore \
            google-cloud-secret-manager \
            google-api-core \
            proto-plus \
            proto \
            kiteconnect \
            openai \
            pydantic \
            six
      - name: Lint with flake8
        run: flake8 .

      - name: Security check with Bandit
        run: bandit -r . -c bandit.yaml

      - name: Run tests (skip faiss tests via pytest.ini)
        run: pytest
