name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install "numpy<2.0.0"
          pip install flake8 bandit pytest
          pip install -r requirements.txt

      - name: Lint with flake8 (respects .flake8 config)
        run: flake8 .

      - name: Security check with Bandit
        run: bandit -r . -c bandit.yaml

      - name: Run Tests
        run: pytest --ignore=test_gpt_monitor.py --ignore=test_rag_runner.py
